### ISSUE TITLE
按照README.md配置环境时出错

### ISSUE THREAD

**Issue by Wenjun-Ji** [ChunmingHe/WS-SAM#5]
Note that WS-SAM is only tested on Ubuntu OS with the following environments.
Creating a virtual environment in the terminal: conda create -n FEDER python=3.8.
Installing necessary packages: pip install -r requirements.txt

以上条件均满足，报错：

(FEDER) root@4e2t57d79ldj6-0:/zhaotingfeng/jiwenjun/WS-SAM# pip install -r requirements.txt 
ERROR: Invalid requirement: '_libgcc_mutex=0.1=main': Expected package name at the start of dependency specifier
    _libgcc_mutex=0.1=main
    ^ (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

作者之前的一篇[工作](https://github.com/ChunmingHe/FEDER)的requirements.txt和这个差不多，issue里也有这个问题，哪个回答里也没有合适的解决方案

**Comment by ChunmingHe** [comment]
加我微信 15112561951
帮你看下

WenJun Ji ***@***.***> 于2024年10月16日周三 14:20写道：

**Comment by Wenjun-Ji** [comment]
感谢，已解决

**Comment by HaoLiu90210** [comment]
我遇到了相同的问题，请问如何解决（哭泣）
